from enum import Enum

class HybridStrategy(Enum):
    SIMULTANEOUS_QKD_PQC = 'SIMULTANEOUS_QKD_PQC'
    PQC_DEFAULT_QKD_LAYER = 'PQC_DEFAULT_QKD_LAYER'
    QKD_PRIMARY_PQC_FALLBACK = 'QKD_PRIMARY_PQC_FALLBACK'
    ADAPTIVE_SWITCHING = 'ADAPTIVE_SWITCHING'
